# Generated by Django 3.2.9 on 2021-11-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(null=True, upload_to='candidates'),
        ),
    ]
