# Generated by Django 3.2.9 on 2021-11-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
